#!/bin/bash
set -e

OUTPUT_DIR="bin"
JS_COMPILER_JAR="closure-compiler/compiler.jar"
JS_OUTPUT="$OUTPUT_DIR/engine.js"
JS_COMPILE="python2.6 closure-library/closure/bin/build/closurebuilder.py \
 --root=closure-library/ \
 --root=src/ \
 --namespace=illandril.game.Engine \
 --output_mode=compiled \
 --compiler_jar=$JS_COMPILER_JAR \
 --compiler_flags=--compilation_level=SIMPLE_OPTIMIZATIONS \
 --compiler_flags=--formatting=PRETTY_PRINT \
 "
# --compiler_flags=--compilation_level=ADVANCED_OPTIMIZATIONS \
# --compiler_flags=--compilation_level=SIMPLE_OPTIMIZATIONS \
# --compiler_flags=--compilation_level=WHITESPACE_ONLY \

CSS_COMPILE_CMD="cat"
CSS_FILES="styles/*.css"
CSS_OUTPUT="$OUTPUT_DIR/engine.css"
CSS_COMPILE="$CSS_COMPILE_CMD $CSS_FILES"

$JS_COMPILE > $JS_OUTPUT
$CSS_COMPILE > $CSS_OUTPUT

