// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../game-engine/src/ai/ai.js', ['illandril.game.ai'], ['goog.array']);
goog.addDependency('../../../game-engine/src/controls/action.js', ['illandril.game.controls.action'], []);
goog.addDependency('../../../game-engine/src/controls/keyHandler.js', ['illandril.game.controls.keyHandler'], ['goog.events', 'goog.events.EventType', 'goog.events.KeyCodes', 'goog.events.KeyHandler', 'goog.events.KeyNames', 'goog.userAgent']);
goog.addDependency('../../../game-engine/src/game.js', ['illandril.game.game'], ['illandril.game.ai', 'illandril.game.controls.keyHandler', 'illandril.game.requestAnimFrame', 'illandril.game.ui.animation', 'illandril.game.ui.ui', 'illandril.game.ui.viewport', 'illandril.game.world', 'goog.array']);
goog.addDependency('../../../game-engine/src/gameObject.js', ['illandril.game.gameObject'], []);
goog.addDependency('../../../game-engine/src/gameTypes/platformer.js', ['illandril.game.platformer'], ['Box2D.Collision.Shapes.b2PolygonShape', 'Box2D.Collision.b2WorldManifold', 'Box2D.Common.Math.b2Vec2', 'illandril.game.controls.action']);
goog.addDependency('../../../game-engine/src/games/mario.js', ['mario'], ['Box2D.Common.Math.b2Vec2', 'illandril.game.controls.keyHandler', 'illandril.game.controls.action', 'illandril.game.game', 'illandril.game.platformer', 'goog.events.KeyCodes']);
goog.addDependency('../../../game-engine/src/games/pit.js', ['pit'], ['Box2D.Collision.Shapes.b2CircleShape', 'Box2D.Common.Math.b2Vec2', 'illandril.game.controls.keyHandler', 'illandril.game.controls.action', 'illandril.game.game', 'illandril.game.platformer', 'goog.events.KeyCodes']);
goog.addDependency('../../../game-engine/src/games/test.js', ['test'], ['Box2D.Collision.Shapes.b2CircleShape', 'Box2D.Collision.Shapes.b2PolygonShape', 'Box2D.Common.Math.b2Vec2', 'Box2D.Dynamics.Joints.b2RevoluteJointDef', 'Box2D.Dynamics.Joints.b2WeldJointDef', 'illandril.game.controls.keyHandler', 'illandril.game.controls.action', 'illandril.game.game', 'illandril.game.platformer', 'goog.events.KeyCodes']);
goog.addDependency('../../../game-engine/src/shims.js', ['illandril.game.requestAnimFrame'], []);
goog.addDependency('../../../game-engine/src/ui/animation.js', ['illandril.game.ui.animation'], ['Box2D.Common.Math.b2Vec2', 'illandril.game.ui.spriteSheet', 'illandril.game.ui.viewport']);
goog.addDependency('../../../game-engine/src/ui/spriteSheet.js', ['illandril.game.ui.spriteSheet'], ['Box2D.Common.Math.b2Vec2', 'illandril.game.ui.ui']);
goog.addDependency('../../../game-engine/src/ui/ui.js', ['illandril.game.ui.ui'], []);
goog.addDependency('../../../game-engine/src/ui/viewport.js', ['illandril.game.ui.viewport'], ['Box2D.Collision.b2AABB', 'Box2D.Common.Math.b2Vec2', 'Box2D.Dynamics.b2DebugDraw', 'illandril.game.ui.spriteSheet', 'illandril.game.ui.ui']);
goog.addDependency('../../../game-engine/src/world.js', ['illandril.game.world'], ['Box2D.Collision.Shapes.b2PolygonShape', 'Box2D.Common.Math.b2Vec2', 'Box2D.Dynamics.b2BodyDef', 'Box2D.Dynamics.b2ContactFilter', 'Box2D.Dynamics.b2FixtureDef', 'Box2D.Dynamics.b2World', 'illandril.game.gameObject', 'illandril.game.ui.viewport']);
