// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../box2d/illandril/Box2D.js', ['Box2D'], ['Box2D.Post']);
goog.addDependency('../../../box2d/illandril/base.js', ['Box2D.inherit', 'Box2D.generateCallback', 'Box2D.is', 'Box2D.Queue', 'Box2D.Consts', 'Box2D.postDefs', 'Box2D.defineProperty'], []);

goog.addDependency('../../../box2d/illandril/collision/b2AABB.js', ['Box2D.Collision.b2AABB'], ['Box2D.Common.Math.b2Vec2']);

goog.addDependency('../../../box2d/illandril/collision/b2Collision.js', ['Box2D.Collision.b2Collision'], ['Box2D.postDefs', 'Box2D.Collision.ClipVertex', 'Box2D.Collision.b2Manifold', 'Box2D.Common.b2Settings']);
goog.addDependency('../../../box2d/illandril/collision/b2ContactID.js', ['Box2D.Collision.b2ContactID'], ['Box2D.defineProperty', 'Box2D.Collision.Features']);
goog.addDependency('../../../box2d/illandril/collision/b2ContactPoint.js', ['Box2D.Collision.b2ContactPoint'], ['Box2D.Common.Math.b2Vec2', 'Box2D.Collision.b2ContactID']);
goog.addDependency('../../../box2d/illandril/collision/b2Distance.js', ['Box2D.Collision.b2Distance'], ['Box2D.Common.b2Settings', 'Box2D.Common.Math.b2Math', 'Box2D.Common.Math.b2Vec2', 'Box2D.postDefs']);
goog.addDependency('../../../box2d/illandril/collision/b2DistanceInput.js', ['Box2D.Collision.b2DistanceInput'], []);
goog.addDependency('../../../box2d/illandril/collision/b2DistanceOutput.js', ['Box2D.Collision.b2DistanceOutput'], ['Box2D.Common.Math.b2Vec2']);
goog.addDependency('../../../box2d/illandril/collision/b2DistanceProxy.js', ['Box2D.Collision.b2DistanceProxy'], ['Box2D.Collision.Shapes.b2Shape', 'Box2D.Common.b2Settings']);
goog.addDependency('../../../box2d/illandril/collision/b2DynamicTree.js', ['Box2D.Collision.b2DynamicTree'], ['Box2D.Collision.b2RayCastInput', 'Box2D.Collision.b2AABB', 'Box2D.Collision.b2DynamicTreeNode', 'Box2D.Common.b2Settings', 'Box2D.Common.Math.b2Math']);
goog.addDependency('../../../box2d/illandril/collision/b2DynamicTreeBroadPhase.js', ['Box2D.Collision.b2DynamicTreeBroadPhase'], ['Box2D.Collision.b2DynamicTree', 'Box2D.Collision.b2DynamicTreePair', 'Box2D.Collision.IBroadPhase']);
goog.addDependency('../../../box2d/illandril/collision/b2DynamicTreeNode.js', ['Box2D.Collision.b2DynamicTreeNode'], ['Box2D.Collision.b2AABB']);
goog.addDependency('../../../box2d/illandril/collision/b2DynamicTreePair.js', ['Box2D.Collision.b2DynamicTreePair'], []);
goog.addDependency('../../../box2d/illandril/collision/b2Manifold.js', ['Box2D.Collision.b2Manifold'], ['Box2D.Common.b2Settings', 'Box2D.Common.Math.b2Vec2', 'Box2D.Collision.b2ManifoldPoint', 'Box2D.postDefs']);
goog.addDependency('../../../box2d/illandril/collision/b2ManifoldPoint.js', ['Box2D.Collision.b2ManifoldPoint'], ['Box2D.Common.Math.b2Vec2', 'Box2D.Collision.b2ContactID']);
goog.addDependency('../../../box2d/illandril/collision/b2RayCastInput.js', ['Box2D.Collision.b2RayCastInput'], ['Box2D.Common.Math.b2Vec2']);
goog.addDependency('../../../box2d/illandril/collision/b2RayCastOutput.js', ['Box2D.Collision.b2RayCastOutput'], ['Box2D.Common.Math.b2Vec2']);
goog.addDependency('../../../box2d/illandril/collision/b2Segment.js', ['Box2D.Collision.b2Segment'], ['Box2D.Common.Math.b2Vec2']);
goog.addDependency('../../../box2d/illandril/collision/b2SeparationFunction.js', ['Box2D.Collision.b2SeparationFunction'], ['Box2D.Common.b2Settings', 'Box2D.Common.Math.b2Vec2', 'Box2D.Common.Math.b2Math', 'Box2D.postDefs']);
goog.addDependency('../../../box2d/illandril/collision/b2Simplex.js', ['Box2D.Collision.b2Simplex'], ['Box2D.Common.b2Settings', 'Box2D.Common.Math.b2Vec2', 'Box2D.Common.Math.b2Math', 'Box2D.Collision.b2SimplexVertex']);
goog.addDependency('../../../box2d/illandril/collision/b2SimplexCache.js', ['Box2D.Collision.b2SimplexCache'], []);
goog.addDependency('../../../box2d/illandril/collision/b2SimplexVertex.js', ['Box2D.Collision.b2SimplexVertex'], []);
goog.addDependency('../../../box2d/illandril/collision/b2TimeOfImpact.js', ['Box2D.Collision.b2TimeOfImpact'], ['Box2D.postDefs', 'Box2D.Collision.b2SimplexCache', 'Box2D.Collision.b2DistanceInput', 'Box2D.Collision.b2DistanceOutput', 'Box2D.Collision.b2SeparationFunction', 'Box2D.Common.Math.b2Transform', 'Box2D.Common.b2Settings', 'Box2D.Collision.b2Distance']);
goog.addDependency('../../../box2d/illandril/collision/b2TOIInput.js', ['Box2D.Collision.b2TOIInput'], ['Box2D.Collision.b2DistanceProxy', 'Box2D.Common.Math.b2Sweep']);
goog.addDependency('../../../box2d/illandril/collision/b2WorldManifold.js', ['Box2D.Collision.b2WorldManifold'], ['Box2D.Collision.b2Manifold', 'Box2D.Common.b2Settings', 'Box2D.Common.Math.b2Vec2', 'Box2D.Consts']);
goog.addDependency('../../../box2d/illandril/collision/ClipVertex.js', ['Box2D.Collision.ClipVertex'], ['Box2D.Common.Math.b2Vec2', 'Box2D.Collision.b2ContactID']);
goog.addDependency('../../../box2d/illandril/collision/Features.js', ['Box2D.Collision.Features'], ['Box2D.defineProperty']);
goog.addDependency('../../../box2d/illandril/collision/IBroadPhase.js', ['Box2D.Collision.IBroadPhase'], []);

goog.addDependency('../../../box2d/illandril/collision/shapes/b2CircleShape.js', ['Box2D.Collision.Shapes.b2CircleShape'], ['Box2D.Common.Math.b2Vec2', 'Box2D.Collision.Shapes.b2Shape', 'Box2D.is', 'Box2D.Common.Math.b2Math']);
goog.addDependency('../../../box2d/illandril/collision/shapes/b2EdgeChainDef.js', ['Box2D.Collision.Shapes.b2EdgeChainDef'], []);
goog.addDependency('../../../box2d/illandril/collision/shapes/b2EdgeShape.js', ['Box2D.Collision.Shapes.b2EdgeShape'], ['Box2D.Common.Math.b2Vec2', 'Box2D.Collision.Shapes.b2Shape', 'Box2D.Common.Math.b2Math', 'Box2D.Common.b2Settings']);
goog.addDependency('../../../box2d/illandril/collision/shapes/b2Shape.js', ['Box2D.Collision.Shapes.b2Shape'], ['Box2D.postDefs', 'Box2D.Collision.b2DistanceInput', 'Box2D.Collision.b2DistanceProxy', 'Box2D.Collision.b2DistanceOutput', 'Box2D.Collision.b2SimplexCache', 'Box2D.Collision.b2Distance']);

goog.addDependency('../../../box2d/illandril/common/b2Settings.js', ['Box2D.Common.b2Settings'], ['Box2D.postDefs']);

goog.addDependency('../../../box2d/illandril/common/math/b2Mat22.js', ['Box2D.Common.Math.b2Mat22'], ['Box2D.Common.Math.b2Vec2']);
goog.addDependency('../../../box2d/illandril/common/math/b2Mat33.js', ['Box2D.Common.Math.b2Mat33'], ['Box2D.Common.Math.b2Vec3']);
goog.addDependency('../../../box2d/illandril/common/math/b2Math.js', ['Box2D.Common.Math.b2Math'], ['Box2D.Common.Math.b2Mat22', 'Box2D.Common.Math.b2Vec2']);
goog.addDependency('../../../box2d/illandril/common/math/b2Transform.js', ['Box2D.Common.Math.b2Transform'], ['Box2D.Common.Math.b2Mat22', 'Box2D.Common.Math.b2Vec2']);
goog.addDependency('../../../box2d/illandril/common/math/b2Sweep.js', ['Box2D.Common.Math.b2Sweep'], ['Box2D.Common.Math.b2Vec2']);
goog.addDependency('../../../box2d/illandril/common/math/b2Vec2.js', ['Box2D.Common.Math.b2Vec2'], []);
goog.addDependency('../../../box2d/illandril/common/math/b2Vec3.js', ['Box2D.Common.Math.b2Vec3'], []);
goog.addDependency('../../../box2d/illandril/dynamics/_dynamics.js', ['Box2D.Dynamics', 'Box2D.Dynamics.b2DebugDraw'], ['Box2D.postDefs']);
goog.addDependency('../../../box2d/illandril/dynamics/contacts/_contacts.js', ['Box2D.Dynamics.Contacts'], ['Box2D.inherit', 'Box2D.postDefs']);
goog.addDependency('../../../box2d/illandril/post.js', ['Box2D.Post'], ['Box2D.unopped', 'Box2D.postDefs']);
goog.addDependency('../../../box2d/illandril/unopped.js', ['Box2D.unopped'], ['Box2D.defineProperty', 'Box2D.Collision.Shapes.b2EdgeShape', 'Box2D.Collision.Shapes.b2EdgeChainDef', 'Box2D.Collision.Shapes.b2CircleShape', 'Box2D.Collision.b2WorldManifold', 'Box2D.Common.Math.b2Sweep', 'Box2D.Common.Math.b2Transform', 'Box2D.Collision.b2TOIInput', 'Box2D.Collision.b2TimeOfImpact', 'Box2D.Collision.b2SimplexVertex', 'Box2D.Collision.b2Simplex', 'Box2D.Collision.b2SeparationFunction', 'Box2D.Collision.b2Segment', 'Box2D.Collision.b2RayCastOutput', 'Box2D.Collision.b2RayCastInput', 'Box2D.Collision.b2Manifold', 'Box2D.Collision.Shapes.b2Shape', 'Box2D.Common.b2Settings', 'Box2D.Collision.b2AABB', 'Box2D.Collision.b2SimplexCache', 'Box2D.Collision.b2Collision', 'Box2D.Collision.b2ContactID', 'Box2D.Collision.b2ContactPoint', 'Box2D.Collision.b2Distance', 'Box2D.Collision.b2DistanceInput', 'Box2D.Collision.b2DistanceOutput', 'Box2D.Collision.b2DistanceProxy', 'Box2D.Collision.b2DynamicTreeBroadPhase', 'Box2D.Collision.b2DynamicTreeNode', 'Box2D.Collision.b2DynamicTree', 'Box2D.Collision.IBroadPhase', 'Box2D.Common.Math.b2Math', 'Box2D.Common.Math.b2Vec2', 'Box2D.Common.Math.b2Vec3', 'Box2D.Common.Math.b2Mat22', 'Box2D.Common.Math.b2Mat33', 'Box2D.Dynamics', 'Box2D.Dynamics.Contacts', 'Box2D.inherit', 'Box2D.generateCallback', 'Box2D.is', 'Box2D.Queue', 'Box2D.postDefs', 'Box2D.Consts']);
