// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../box2d/illandril/Box2D.js', ['Box2D'], ['Box2D.Collision', 'Box2D.Collision.b2DynamicTree', 'Box2D.Common.Math.b2Math', 'Box2D.Common.Math.b2Vec2', 'Box2D.Dynamics', 'Box2D.Dynamics.Contacts', 'Box2D.Post', 'Box2D.base', 'Box2D.unopped']);
goog.addDependency('../box2d/illandril/base.js', ['Box2D.base'], []);
goog.addDependency('../box2d/illandril/collision/_collision.js', ['Box2D.Collision'], ['Box2D.base']);
goog.addDependency('../box2d/illandril/collision/b2DynamicTree.js', ['Box2D.Collision.b2DynamicTree'], ['Box2D.Collision']);
goog.addDependency('../box2d/illandril/common/math/b2Math.js', ['Box2D.Common.Math.b2Math'], []);
goog.addDependency('../box2d/illandril/common/math/b2Vec2.js', ['Box2D.Common.Math.b2Vec2'], ['Box2D.Common.Math.b2Math']);
goog.addDependency('../box2d/illandril/dynamics/_dynamics.js', ['Box2D.Dynamics'], ['Box2D.base']);
goog.addDependency('../box2d/illandril/dynamics/contacts/_contacts.js', ['Box2D.Dynamics.Contacts'], ['Box2D.base']);
goog.addDependency('../box2d/illandril/post.js', ['Box2D.Post'], ['Box2D.unopped']);
goog.addDependency('../box2d/illandril/unopped.js', ['Box2D.unopped'], ['Box2D.Collision', 'Box2D.Dynamics', 'Box2D.Dynamics.Contacts']);
